apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: icecreamflavorrecommendation-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lg0m3s/icecreamflavorrecomendation.git
    targetRevision: main
    path: k8s  # The directory containing the K8s manifests, including jira-update
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true