apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-read-access-binding
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: default
  namespace: argocd
roleRef:
  kind: Role
  name: argocd-read-access
  apiGroup: rbac.authorization.k8s.io
