apiVersion: v1
kind: Service
metadata:
  name: icecreamflavorrecommendation-app
  namespace: default
spec:
  selector:
    app: icecreamflavorrecommendation-app
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort