apiVersion: v1
kind: Service
metadata:
  name: icecreamflavorrecommendation-app
  namespace: default
spec:
  selector:
    app: icecreamflavorrecommendation-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP